name: Enable PSTLIB

on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v2
            
            - name: Enable file
              if: ${{ hashFiles('PST_Disabled.js') != '' }}
              run: mv -v PST_Disabled.js PST_Lib.js

            - name: Push Changes
              run: |
               git config user.name github-actions
               git config user.email github-actions@github.com
               git add .
               git commit -m "Toggled PST_Lib"
               git push
               curl  -H "Authorization: Bearer secrets.NTFY_TOKEN" -d "PSTOOL Enabled" ntfy.cultlear.com/PSTool
